# Generated by Django 5.0.6 on 2025-09-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='service_images/')),
                ('type_of_art', models.CharField(max_length=100)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('userupload_id', models.IntegerField()),
                ('userupload_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'service_images',
            },
        ),
    ]
