# Generated by Django 5.0.6 on 2025-09-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='userupload_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='userupload_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
