# Generated by Django 5.0.6 on 2025-10-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_serviceimage_userupload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='is_verified_pic',
            field=models.BooleanField(default=False),
        ),
    ]
