# Generated by Django 5.0.6 on 2025-11-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_serviceimage_is_verified_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='min_size',
            field=models.CharField(default='', max_length=50),
        ),
    ]
