# Generated by Django 5.0.6 on 2025-10-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gst_no',
            field=models.CharField(blank=True, help_text='GST Number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Organization/Company Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_card',
            field=models.CharField(blank=True, help_text='PAN Card Number', max_length=10, null=True),
        ),
    ]
