# Generated by Django 5.0.6 on 2025-11-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_gst_no_employee_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='belong_to_org',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
