# Generated by Django 5.0.6 on 2025-11-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee_belong_to_org_employee_full_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='block_status',
            field=models.BooleanField(default=False),
        ),
    ]
