# Generated by Django 5.0.6 on 2025-09-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_serviceimage_userupload_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='userupload_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='userupload_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
