# Generated by Django 5.0.6 on 2025-09-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_serviceimage_userupload_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='userupload_id',
            field=models.IntegerField(default=0),
        ),
    ]
