# Generated by Django 5.0.6 on 2025-09-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking_design_names_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_design',
            field=models.ImageField(blank=True, null=True, upload_to='customer_designs/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_of_design',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
