# Generated by Django 5.0.6 on 2025-09-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='customer_id',
            field=models.CharField(max_length=50),
        ),
    ]
