# Generated by Django 5.0.6 on 2026-02-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bookingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='artist_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_status',
            field=models.BooleanField(default=False),
        ),
    ]
