# Generated by Django 4.2.7 on 2025-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=150, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar_card_no', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('aadhar_card_image_front', models.ImageField(blank=True, null=True, upload_to='aadhar_cards/front/')),
                ('aadhar_card_image_back', models.ImageField(blank=True, null=True, upload_to='aadhar_cards/back/')),
                ('experience', models.PositiveIntegerField(blank=True, help_text='Experience in years', null=True)),
                ('type_of_work', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_work_location', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='passport_photos/')),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_no', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
