# Generated by Django 5.2.6 on 2025-09-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_role_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_full_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_password', models.CharField(max_length=128)),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='customer_photos/')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
